### ISSUE TITLE
迁移到 mirai

### ISSUE THREAD

**Issue by bytemain** [Kelab/iswust_bot#27]
- [ ] dockerfile

**Comment by Egrt** [comment]
可以给个联系方式吗，想请教下js模拟登录教务处的操作，校友可以加下我QQ766529835

**Comment by bytemain** [comment]
> 可以给个联系方式吗，想请教下js模拟登录教务处的操作，校友可以加下我QQ766529835

可以看看 python 版本的实现 https://github.com/BudyLab/auth_swust

**Comment by Egrt** [comment]
> o

之前看了，还是有点问题想问

**Comment by bytemain** [comment]
> > o
> 
> 之前看了，还是有点问题想问

可以在那个仓库开个 issue，我回复你就行了。
也可以让其他有相同问题的人看到
